let game = {
    name: "Rock, Paper and Scissors",
    owner: "Me",
    useFor: "Exercise 20",

    choice: ["ROCK", "PAPER", "SCISSORS"],
    winner: `<i class ="text-danger fa fa-beat-fade winner">W i n n e r!</i>`,
    loser: `<i class ="text-dark fa loser">Try Again</i>`,

    //Function of the game
    theGame(userChoice) {

    //Generate Random Number
    let uChoice = Number(userChoice);
    let rNumber = Math.random();
   
    // let mCeil = Math.ceil(rNumber) * 3;
    // let mFloor = Math.floor(rNumber* 3);
     let mRound = Math.round(rNumber * 2);
    // alert(mRound);
    // alert("Your choice is: " + uChoice);
    // Evaluates user choice from index file and compare with rounded randome number generated by random() method
    switch (uChoice) {
        case 0: 
            if (mRound == 0) {
                let yChoice = `<i class="fa-solid fa-hill-rockslide"></i>`;
                let yResult = "It's a DRAW, Try again!";
                let cChoice = `<i class="fa-solid fa-hill-rockslide"></i>`;
                let cResult = "It's a DRAW, Try again!";
                document.getElementById("yourChoice").innerHTML = yChoice;
                document.getElementById("yourResult").innerHTML = yResult;
                document.getElementById("computerChoice").innerHTML = cChoice;
                document.getElementById("computerResult").innerHTML = cResult;
                
            }else if(mRound == 1) { //Computer random choice is 1 = paper
                // alert("Computer Choice is " + this.choice[mRound] + "; You LOST" );
                let yChoice = `<i class="fa-solid fa-hill-rockslide"></i>`;
                let yResult = this.loser;
                let cChoice = `<i class="fa-solid fa-map"></i>`;
                let cResult = this.winner;
                document.getElementById("yourChoice").innerHTML = yChoice;
                document.getElementById("yourResult").innerHTML = yResult;
                document.getElementById("computerChoice").innerHTML = cChoice;
                document.getElementById("computerResult").innerHTML = cResult;

            } else if (mRound == 2) {
                let yChoice = `<i class="fa-solid fa-hill-rockslide"></i>`;
                let yResult = this.winner;
                let cChoice = `<i class="fa-solid fa-scissors"></i>`;
                let cResult = this.loser;
                document.getElementById("yourChoice").innerHTML = yChoice;
                document.getElementById("yourResult").innerHTML = yResult;
                document.getElementById("computerChoice").innerHTML = cChoice;
                document.getElementById("computerResult").innerHTML = cResult;
            }else {
                alert("Something went wrong, case 0");
            }
            break;
         case 1: 
            if (mRound == 0) {
                // let yChoice = `<i class="fa-solid fa-hill-rockslide"></i>`;
                let yChoice = `<i class="fa-solid fa-map"></i>`;
                let yResult = this.winner;
                let cChoice = `<i class="fa-solid fa-hill-rockslide"></i>`;
                let cResult = this.loser;
                document.getElementById("yourChoice").innerHTML = yChoice;
                document.getElementById("yourResult").innerHTML = yResult;
                document.getElementById("computerChoice").innerHTML = cChoice;
                document.getElementById("computerResult").innerHTML = cResult;
                
            }else if(mRound == 1) { //Computer random choice is 1 = paper
                // alert("Computer Choice is " + this.choice[mRound] + "; You LOST" );
                let yChoice = `<i class="fa-solid fa-map"></i>`;
                let yResult = `It's a DRAW, Try again!`;
                let cChoice = `<i class="fa-solid fa-map"></i>`;
                let cResult = `It's a DRAW, Try again!`;
                document.getElementById("yourChoice").innerHTML = yChoice;
                document.getElementById("yourResult").innerHTML = yResult;
                document.getElementById("computerChoice").innerHTML = cChoice;
                document.getElementById("computerResult").innerHTML = cResult;

            } else if (mRound == 2) {
                let yChoice = `<i class="fa-solid fa-map"></i>`;
                let yResult = this.loser;
                let cChoice = `<i class="fa-solid fa-scissors"></i>`;
                let cResult = this.winner;
                document.getElementById("yourChoice").innerHTML = yChoice;
                document.getElementById("yourResult").innerHTML = yResult;
                document.getElementById("computerChoice").innerHTML = cChoice;
                document.getElementById("computerResult").innerHTML = cResult;

            }else {
                alert("Something went wrong, case 1");
            }
            break;
        case 2: 
            // if (mRound == 0) {
            //     alert ("Computer Choice is " + this.choice[mRound] + "; You LOST");
            // }else if (mRound == 1)  {
            //     alert ("Computer Choice is " + this.choice[mRound] + "; You WON" );
            // }else if (mRound == 2) {
            //     alert ("Computer Choice is " + this.choice[mRound] + "; it's a DRAW" );
            if (mRound == 0) {
                // let yChoice = `<i class="fa-solid fa-hill-rockslide"></i>`;
                let yChoice = `<i class="fa-solid fa-scissors"></i>`;
                let yResult = this.loser;
                let cChoice = `<i class="fa-solid fa-hill-rockslide"></i>`;
                let cResult = this.winner;
                document.getElementById("yourChoice").innerHTML = yChoice;
                document.getElementById("yourResult").innerHTML = yResult;
                document.getElementById("computerChoice").innerHTML = cChoice;
                document.getElementById("computerResult").innerHTML = cResult;
                
            }else if(mRound == 1) { //Computer random choice is 1 = paper
                // alert("Computer Choice is " + this.choice[mRound] + "; You LOST" );
                let yChoice = `<i class="fa-solid fa-scissors"></i>`;
                let yResult = this.winner;
                let cChoice = `<i class="fa-solid fa-map"></i>`;
                let cResult = this.loser;
                document.getElementById("yourChoice").innerHTML = yChoice;
                document.getElementById("yourResult").innerHTML = yResult;
                document.getElementById("computerChoice").innerHTML = cChoice;
                document.getElementById("computerResult").innerHTML = cResult;

            } else if (mRound == 2) {
                let yChoice = `<i class="fa-solid fa-scissors"></i>`;
                let yResult = `It's a DRAW, Try again!`;
                let cChoice = `<i class="fa-solid fa-scissors"></i>`;
                let cResult = `It's a DRAW, Try again!`;
                document.getElementById("yourChoice").innerHTML = yChoice;
                document.getElementById("yourResult").innerHTML = yResult;
                document.getElementById("computerChoice").innerHTML = cChoice;
                document.getElementById("computerResult").innerHTML = cResult;

            }else {
                alert("Something went wrong, case 2")
           }
        break;
        default: alert("Something went wrong, case end")
    }

    // let compChoice = this.choice[mRound];
    // alert("Computer choice is: " +  compChoice);
    
    }

};
//game.theGame();